### ISSUE TITLE
[BUG] process.env.npm_config_user_agent missing in v7

### ISSUE THREAD

**Issue by rafgraph** [npm/cli#1834]
### Current Behavior:
`npm i --save-dev husky` doesn't run the install and postinstall scripts after installing the package so the git hooks are never setup. No error is thrown. I haven't checked to see if this is unique to the `husky` package or not.

### Expected Behavior:
For the install and postinstall scripts to run after the package is installed and the git hooks to be set up.

### Steps To Reproduce:
`npm i --save-dev husky`
Then check to see if the git hooks have been added to `.git/hooks/pre-commit` (compare this to installing using npm v6)

### Environment:

- OS: MacOS 10.15.6
- Node: 12.18.3
- npm: v7.0.0-beta.11

**Comment by nlf** [comment]
So there's a few things happening here:

1. We no longer display the output of install scripts unless an error occurs, this is deliberate and intended to reduce the amount of text we print during an install process.

2. The script actually _is_ running, and failing, the problem is that it is not setting the `process.exitCode` to a non-0 value when an error occurs, so npm does not print the error. The error in question is

```
husky > Setting up git hooks
Cannot destructure property 'name' of 'which_pm_runs_1.default(...)' as it is undefined.
husky > Failed to install
```

3. The current version of husky (4.x) relies on the package [which-pm-runs](https://github.com/zkochan/which-pm-runs) which relies on `process.env.npm_config_user_agent` being populated, which was removed from the environment variables that npm 7 provides. This is something that we will consider re-adding to help reduce friction.

**Comment by rafgraph** [comment]
Thanks for the detailed explanation. I don't work on `husky` so can't say what their thoughts are on this.

**Comment by nlf** [comment]
we published v7.0.0-rc.4 today that resolves this

**Comment by rafgraph** [comment]
Thanks @nlf, however I'm still getting the same result with `husky`, the hooks aren't setup when running install. Maybe there is another suppressed error? I tried `npm i --save-dev husky --loglevel silly` but nothing unusual shows up, is there another command that I can use to see all the output like v6?

**Comment by rafgraph** [comment]
@nlf still having an issue with installing husky on v7.0.3. Should I open a new issue? Thanks.

**Comment by ssamakar** [comment]
Same here with v7.4.2.

**Comment by nlf** [comment]
if the issue is that the `npm_config_user_agent` environment variable isn't set, then we should reopen this issue. if you're having another problem entirely, then yes please do open a new issue.

**Comment by alexander-mai** [comment]
I have the problem that ```npm_config_user_agent``` is not defined on Version 7.7.2. When I switch back to 7.6.x the value is set.

**Comment by jspivack** [comment]
@nlf @alexander-mai getting the same bug in 7.7.4

**Comment by nlf** [comment]
Can one of you please open a new issue for this? We'll take a look ASAP

**Comment by alexander-mai** [comment]
I opened a new Issue: https://github.com/npm/cli/issues/2960.
