### ISSUE TITLE
[BUG] npm 7.x ignores publishConfig.registry

### ISSUE THREAD

**Issue by marcusds** [npm/cli#1937]
### Current Behavior:
`npm publish` does not follow `publishConfig.registry`, if registry is `.npmrc` it will try to publish to that, if not npm.org.

### Expected Behavior:
`npm publish` publish to defined `publishConfig.registry` as it did in 6.x.

### Steps To Reproduce:
* Install npm@latest-7
* Set `publishConfig.registry` IE: `"publishConfig": { "registry": "https://..." }`
* Run `npm publish`

### Environment:
- OS: Windows 10
- Node: 12.18.1
- npm: 7.0.0-rc.3

**Comment by nlf** [comment]
this should be resolved! can you update to 7.0.1 with `npm i -g npm@next-7` and see if it takes care of it for you?

**Comment by thw0rted** [comment]
I'm using 7.3.0 and still seeing this behavior, specifically, it fails with ENEEDAUTH immediately when I run `npm publish`, even though I'm logged in to the (private) repo specified in `publishConfig.registry`.

Reverting to 6.14.10 fixes it, as does manually specifying `npm publish --registry=...`.  I haven't tried an earlier version of 7 (like 7.0.1) to see if it worked in October but re-broke afterwards.

**Comment by transcranial** [comment]
I can confirm this bug exists in 7.3.0.

**Comment by MikaelX** [comment]
I can confirm this bug exists in 7.4.0, and 7.4.3

**Comment by StefanLiebenberg** [comment]
This works for me in 7.2.0 and breaks in 7.3.0.

**Comment by robross0606** [comment]
I can confirm this still exists with 7.5.2 which is now released to GA and breaking 60+ projects on our ci server.

**Comment by wraithgar** [comment]
The `ENEEDAUTH` bug is fixed in https://github.com/npm/cli/pull/2602

**Comment by HoplaGeiss** [comment]
This issue still exist in 7.5.4

**Comment by rndm2** [comment]
It is still reproduced in 7.5.6
Any updates?

**Comment by nlf** [comment]
is the problem you're seeing that we're actually publishing to the wrong registry? or are you getting the `ENEEDAUTH` error?

**Comment by rndm2** [comment]
I am still getting `ENEEDAUTH` error and npm ignore `package.json`'s publish settings.
Reverted to 6.x.x

**Comment by nlf** [comment]
would you mind opening a new issue? the ENEEDAUTH thing is distinct from this original bug. i'll make sure we address this for the next release

**Comment by rndm2** [comment]
I am not sure how to get full publish log. 
`npm publish --verbose` do not show me repo address and http(s) request

**Comment by nlf** [comment]
`npm publish --loglevel=silly` should give you a lot more information

**Comment by HoplaGeiss** [comment]
For me, the issue still is that it's being published to the wrong registry.

**Comment by nlf** [comment]
> For me, the issue still is that it's being published to the wrong registry.

would you mind also opening a new issue? if you can come up with a small reproduction case for us that would be amazing, i haven't been able to reproduce the case where we're publishing to the wrong registry

**Comment by rndm2** [comment]
I'll do this tomorrow morning.

**Comment by maxine-l-m** [comment]
> would you mind opening a new issue? the ENEEDAUTH thing is distinct from this original bug. i'll make sure we address this for the next release

actually, I don't think it's a different issue, it's because the user is authorized for publishConfig.registry but not authorized for the default registry (npm I'm assuming)

**Comment by tbenyon** [comment]
If anyone else lands hear as I did I found running `npm config set registry <registry url>` fixed my issue but I don't understand why.

**Comment by mlechler** [comment]
> If anyone else lands hear as I did I found running `npm config set registry <registry url>` fixed my issue but I don't understand why.

Because this sets the registry in the global .npmrc file.

npm seems to take always the registry from the global .npmrc and ignores any local .npmrc and the publishConfig in the package.json. Still an issue with v10.2.4!?
