### ISSUE TITLE
[BUG] lifecycle scripts not run in workspace packages after install

### ISSUE THREAD

**Issue by peterjuras** [npm/cli#1965]
### Current Behavior:

When running `npm install` in a workspace root, `prepare` scripts of individual workspace packages are not run.

### Expected Behavior:

The expectation would be that running `npm install` in a workspace root would be at least equal to running `npm install` in each individual package (ignoring the additional benefits like hoisting for now).

### Steps To Reproduce:

1. Create a workspace with 2 child packages, or clone this [sample repository](https://github.com/peterjuras/npm-workspaces-lifecycle-scripts-issue)
2. Run `npm install` in the root folder

-> All packages have a prepare script that creates a file in their folder, but only the root prepare script is run. When running npm install in a child package the prepare script is run for this child package.

According to the [workspaces RFC](https://github.com/npm/rfcs/blob/latest/implemented/0026-workspaces.md#detailed-explanation) all dependencies of nested packages should be installed - which is the case - but also all associated lifecycle scripts should be run, which is not the case yet.

A workaround would be to have a top level prepare script which runs the prepare scripts of nested packages, hopefully soon with a `run-script` command as detailed in the [newer workspaces RFC](https://github.com/npm/rfcs/pull/117/files).

### Environment:

OS: independent
Node: v12.18.4
npm: 7.0.0

**Comment by ruyadorno** [comment]
Hi @peterjuras, thanks for the report! We do have a patch lined up already and should land hopefully in the next patch release, just want to make sure it gets some more testing prior to landing it 😊 I'll keep you posted 👍

**Comment by peterjuras** [comment]
Thanks for the quick response. I'm looking forward to using npm 7 in more of our repositories.

**Comment by felschr** [comment]
Has this been released? It doesn't seem to work for me with `npm@7.3.0`.

**Comment by emccorson** [comment]
@felschr I think this was released in `arborist@2.2.0` but `npm@7.5.2` is still locked to `arborist@2.1.1`.

**Comment by ruyadorno** [comment]
hi @felschr @emccorson the original reported issue should have been fixed back in October, are you finding similar problems? If that's the case it would be very appreciated if you can open a new issue providing some more info such as log files, package.json, package-lock.json, etc 😊

**Comment by amatissart** [comment]
Unless I am mistaken about the expected behavior, a similar issue persists with the current version (v7.6.3): #2900

**Comment by basicdays** [comment]
@ruyadorno Yeah I ran into issue #2900 as well, so this issue is partially fixed. Prepare scripts are only ran if the root `package-lock.json` file does _not_ exist.

**Comment by rettgerst** [comment]
this appears to still be affecting v7.12.1.

this issue is a showstopper for typescript monorepos as I rely on the "prepare" script to transpile ts to js.

**Comment by mrgrain** [comment]
With v7.12.1, `prepare` scripts seem to run on `npm ci` but not `npm i` (except when the root node_modules is missing).

It's a bit inconsistent.

**Comment by rettgerst** [comment]
okay, I've come up with my own solution.

I've published the npm package [prepare-workspace-modules](https://www.npmjs.com/package/prepare-workspace-modules). in your root package.json, add it as a devDependency, and then add the command (same name) to your postinstall script. the package will then traverse through your monorepo's dependency tree and run the `prepare` scripts in the proper order.
