### ISSUE TITLE
[BUG] npm outdated ignores proxy and registry configs

### ISSUE THREAD

**Issue by yousifalraheem** [npm/cli#2060]
### Current Behavior:
Runing `npm outdated` will throw an error ignoring the proxy and registry configurations. After upgrading to npm 7, I was unable to run `npm outdated` anymore.

### Expected Behavior:
Should work as intended showing the outdated dependencies.

### Steps To Reproduce:
Steps to reproduce the behavior (You need to run this behind corporate VPN and registry):
1. Set up the proxy and registry settings in the global npm config
2. Navigate to any project with a valid `package.json` that has dependencies
3. Run 'npm outdated'
4. See error...

### Environment:
- OS: Windows 10 Version 1803 Build 17134.1792
- Node: 15.0.1
- npm: 7.0.5

### Screenshots
![image](https://user-images.githubusercontent.com/10633734/97391927-5f61fa00-191b-11eb-9af4-b56d3b464194.png)

**Comment by darcyclarke** [comment]
@yousifalraheem can you try updating your version of `v7` (ie. `npm i -g npm@7`) & trying again? We've fixed a few bugs around setting proxies.

**Comment by joshuaavalon** [comment]
@darcyclarke I am on npm 7.4.2 and Node 15 and I am still facing the same issue. I am behind a proxy. `npm install` and `npm update` works fine but `npm outdated` will throw `getaddrinfo ENOTFOUND` for `registry.npmjs.org`.

**Comment by thirteen-io** [comment]
> @yousifalraheem can you try updating your version of `v7` (ie. `npm i -g npm@7`) & trying again? We've fixed a few bugs around setting proxies.

I've just attempted this. Using `npm i -g npm@7` fails however `npm i -g npm@latest` seems to have resolved the issue.
(Tested with v15.6.0 and v15.4.0 on Windows 10).

**Comment by ljharb** [comment]
@thirteen-io fails how? using “latest” right now installs npm 6.

**Comment by thirteen-io** [comment]
@ljharb Sorry for not being clear.
It failed exactly like the original issue posted. (ENOTFOUND etc)

You are also correct regarding the latest release... totally my mistake sorry. I thought latest was using npm 7. It _is_ at least a temporary workaround for now if you absolutely _need_ the outdated command.

**Comment by joshuaavalon** [comment]
@thirteen-io Using npm 6 is not a workaround if you want to use workspace which only available on npm 7. My workaround is [npm-check-updates](https://www.npmjs.com/package/npm-check-updates). It updates packages in package.json to latest version and I just diff the versions change.
