### ISSUE TITLE
[BUG] NPM v7 private registry authentication 401

### ISSUE THREAD

**Issue by apottere** [npm/cli#2183]
I searched other issues, but I didn't find anything that was specifically this issue.

### Current Behavior:
With a valid (and working) npm v6 `~/.npmrc` that adds authentication for a private registry, npm v7 receives a 401 from the registry for any package (ex: `npm i -g npm@7`).

### Expected Behavior:
npm v7 should authenticate the same way npm v6 does.

### Steps To Reproduce:
My current (redacted) npmrc:
```
progress=true
email="me@company.com"

registry=https://artifactory.company.com/artifactory/api/npm/repo
//artifactory.company.com/artifactory/api/npm/:always-auth=true
//artifactory.company.com/artifactory/api/npm/:username="me@company.com"
//artifactory.company.com/artifactory/api/npm/:password="api_token | base64"
```

Install fresh node 14:
```
$ nvm install 14
Downloading and installing node v14.15.1...
Local cache found: ${NVM_DIR}/.cache/bin/node-v14.15.1-darwin-x64/node-v14.15.1-darwin-x64.tar.xz
Checksums match! Using existing downloaded archive ${NVM_DIR}/.cache/bin/node-v14.15.1-darwin-x64/node-v14.15.1-darwin-x64.tar.xz
Now using node v14.15.1 (npm v6.14.8)
```

Install npm v7 with npm v6 (`$HOME` redacted):
```
$ npm i -g npm@7
/$HOME/.nvm/versions/node/v14.15.1/bin/npm -> /$HOME/.nvm/versions/node/v14.15.1/lib/node_modules/npm/bin/npm-cli.js
/$HOME/.nvm/versions/node/v14.15.1/bin/npx -> /$HOME/.nvm/versions/node/v14.15.1/lib/node_modules/npm/bin/npx-cli.js
+ npm@7.0.11
added 51 packages from 19 contributors, removed 238 packages and updated 196 packages in 6.282s
```

Install npm v7 with npm v7:
```
$ npm i -g npm@7
npm ERR! code E401
npm ERR! Incorrect or missing password.
npm ERR! If you were trying to login, change your password, create an
npm ERR! authentication token or enable two-factor authentication then
npm ERR! that means you likely typed your password in incorrectly.
npm ERR! Please try again, or recover your password at:
npm ERR!     https://www.npmjs.com/forgot
npm ERR! 
npm ERR! If you were doing some other operation then your saved credentials are
npm ERR! probably out of date. To correct this please try logging in again with:
npm ERR!     npm login

npm ERR! A complete log of this run can be found in:
npm ERR!     /$HOME/.npm/_logs/2020-11-16T21_47_31_005Z-debug.log
```

### Environment:

- OS: MacOS 10.15.7
- Node: 14.15.1, also tested 15.x
- npm: 7.0.11

**Comment by apottere** [comment]
Tipped off by #2025, I tried changing the URL of the authentication lines, and found that if I added `repo/` then authentication succeeded in v7:
```
registry=https://artifactory.company.com/artifactory/api/npm/repo
//artifactory.company.com/artifactory/api/npm/repo/:always-auth=true
//artifactory.company.com/artifactory/api/npm/repo/:username="me@company.com"
//artifactory.company.com/artifactory/api/npm/repo/:password="api_token | base64"
```

However, with `repo/` added I can no longer authenticate with npm v6...

Simple but annoying workaround seems to be to duplicate the `always-auth`, `username`, and `password` lines with and without `repo/` for compatibility with both npm v6 and v7.

**Comment by ljharb** [comment]
Do you expect your coworkers to be using "not the identical version of node and npm"? O.o usually these things are mandated to be a single fixed version for any given project.

**Comment by apottere** [comment]
We have over 100 node repos (maybe over 200) within our GitHub Enterprise organization alone, not counting other organizations.  These projects span various deployment patterns and datacenters/clouds, and as such it's difficult to update all of them at once.  So yes, I can guarantee that my coworkers will _never_ be using identical versions of node and npm for all projects.

Edit: Not sure if I misunderstood you, but yes we usually pin the node version and specify a minimum npm version for a _specific project_, but this issue relates to user configuration which affects _all_ projects.

**Comment by ljharb** [comment]
Gotcha, yes, i meant specific projects - and i assumed that per-project npmrc config would be customizeable per project (ie, per npm version) rather than relying it being on the user’s machine.

**Comment by apottere** [comment]
My impression was that user credentials belonged in the user's `~/.npmrc`, and not in the project configuration.  Is that an incorrect assumption?  It seems tedious to have to configure our private registry for each and every project we work on.

**Comment by ljharb** [comment]
Ah, credentials yes; but i assumed the user would run `npm login` themselves - which registry to use i would expect to be configured per project.

**Comment by apottere** [comment]
No, we have a single registry mirror and a tool that aids developers in creating a valid `~/.npmrc` that can authenticate to that registry with their credentials.

**Comment by josselinchevalay** [comment]
hello all,

I'm joining this ticket because currently we are using a jenkins (2.254) and a jfrog artifactory (6.12.1 rev 61201900) and we noticed a strange behavior between npm v6.14.6 (used in 12.18.3) and npm v7.0.3 (used in 15.0.1). 

In npm 6.14.6 it works perfectly with 7.0.3 we can't manage to publish our node js package on our artifactory. 

So on a jenkins job and on the same slave node our jobs fail if we use npm 7 but works fine with npm 6.

After some research in the artifactory logs it seems that npm 7 tries to publish the node js packet without sending the connection credentials because artifactory considers it as a packet sent as an annonym.

Please feel free to contact me if you need more details (logs or if I test something).
Regards

**Comment by Gyllsdorff** [comment]
I got a very similar problem when I tried to update our node version to 15.2.1. We have a private Artifactory npm registry that we proxy all our requests through, our dev laptops have a `ARTIFACTORY_BASE64` env variable with a base 64 encoded username:password, and our projects have a a `.npmrc` with `_auth = ${ARTIFACTORY_BASE64}` & `registry = <our private npm mirror/proxy>`.

That works fine in NPM 6 but in NPM 7 we got HTTP 401 errors, the problem in our case was that our usernames had a `@` in it, we had to urlencode the username and then base64 decode it to get it to work with NPM 7.0.8.

**Comment by quintstoffers** [comment]
I seem to be encountering this issue with a package stored on the GitHub repository (@swydo/byol-cli from https://github.com/Swydo/byol), but only when running `npm install` for the second time. The first install works perfectly fine.

_.npmrc_
```
//npm.pkg.github.com/:_authToken=REDACTED
@swydo:registry=https://npm.pkg.github.com
save-exact=true
package-lock=false
always-auth=true
```

_First run_
`npm install --legacy-peer-deps`
```
added 4069 packages, and audited 4247 packages in 3m
```

_Second run_
`npm install --legacy-peer-deps`
```
npm ERR! code E401
npm ERR! Incorrect or missing password.
npm ERR! If you were trying to login, change your password, create an
npm ERR! authentication token or enable two-factor authentication then
npm ERR! that means you likely typed your password in incorrectly.
npm ERR! Please try again, or recover your password at:
npm ERR!     https://www.npmjs.com/forgot
npm ERR!
npm ERR! If you were doing some other operation then your saved credentials are
npm ERR! probably out of date. To correct this please try logging in again with:
npm ERR!     npm login
```

Debug log:
```
373 verbose stack Error: Unable to authenticate, need: Basic realm="GitHub Package Registry"
373 verbose stack     at /Users/quint/.nvm/versions/node/v15.0.1/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:113:17
373 verbose stack     at processTicksAndRejections (node:internal/process/task_queues:93:5)
374 verbose statusCode 401
375 verbose pkgid https://npm.pkg.github.com/download/@swydo/byol-cli/1.14.19/d513c01df025d93bf0989595c72a06e7f539cc2a69db7d9feda7cac1577717f0
376 verbose cwd /Users/quint/Development/swydo/polder
377 verbose Darwin 19.6.0
378 verbose argv "/Users/quint/.nvm/versions/node/v15.0.1/bin/node" "/Users/quint/.nvm/versions/node/v15.0.1/bin/npm" "install" "--legacy-peer-deps"
379 verbose node v15.0.1
380 verbose npm  v7.0.15
381 error code E401
382 error Incorrect or missing password.
383 error If you were trying to login, change your password, create an
383 error authentication token or enable two-factor authentication then
383 error that means you likely typed your password in incorrectly.
383 error Please try again, or recover your password at:
383 error     https://www.npmjs.com/forgot
383 error
383 error If you were doing some other operation then your saved credentials are
383 error probably out of date. To correct this please try logging in again with:
383 error     npm login
384 verbose exit 1
```

**Comment by Mexx77** [comment]
I see the same issue. With npm 6 it works.
npm version: 7.0.5
private repository: CodeArtifact
error: code E401

**Comment by ljharb** [comment]
What happens with npm v7.3.0?

**Comment by josselinchevalay** [comment]
hi in my side use npm 7.3.0 seems fix my issue. if possible to have some details about that ?

**Comment by Mexx77** [comment]
I can confirm that private repos work again with npm v7.3.0

**Comment by ljharb** [comment]
Great, sounds like this is fixed! Happy to reopen if not (cc @apottere)

**Comment by Mexx77** [comment]
@ljharb realized, I still have the issue with npm v7.3.0 when my CodeArtifact token have been expired. It cannot renew them and fails with a 401 error. npm 6 is able to renew them

**Comment by perrin4869** [comment]
I'm having this same issue authenticating github packages on 7.3.0 (using `authToken`, works in `npm@6`)

**Comment by darcyclarke** [comment]
As per @ljharb's note, the original issue should have been resolved as of `v7.3.0`. If you find yourself having other auth issues, please file a new ticket (utilizing one of our issue templates: https://github.com/npm/cli/issues/new/choose)
