### ISSUE TITLE
[BUG] v 7.3.0 when publishing to private rep You need to authorize this machine using 'npm adduser'

### ISSUE THREAD

**Issue by sysmat** [npm/cli#2453]
### Current Behavior:
Can not publish(This command requires you to be logged in) but I  adduser  successfully 
### Expected Behavior:
 - it work with npm v 6

### Steps To Reproduce:
-  npm adduser --registry=https://zelenjak.arnes.si/nexus/repository/ArnesNpm/
- ok login and in my .npmrc I get
```
registry=https://zelenjak.arnes.si/nexus/repository/ArnesGroupNPM/
//zelenjak.arnes.si/nexus/repository/ArnesNpm/:_authToken=NpmToken.XXXXXXXXX
```
- in my package I have:
```
,
  "publishConfig": {
    "registry": "https://zelenjak.arnes.si/nexus/repository/ArnesNpm/"
  },
```
- when running npm publish I got error:
```
npm ERR! code ENEEDAUTH
npm ERR! need auth This command requires you to be logged in.
npm ERR! need auth You need to authorize this machine using `npm adduser`
```

### Environments:

- Node: 12.6.0
- npm: 7.3.0
- OS: win32 x64

**Comment by ljharb** [comment]
ArnesGroupNpm and ArnesNpm are different registries.

**Comment by sysmat** [comment]
This is nexus:
- ArnesGroupNpm is group repo(combining public and private) and it is for download
- ArnesNpm  is private hosted repo and used for upload
- it works with npm 6
- publishConfig has ArnesNpm  and _authToken in .npmrc is for ArnesNpm

**Comment by ljharb** [comment]
Ah, true - the publishConfig's registry is the one that's authed in npmrc.

**Comment by foxxyz** [comment]
Likely related to #2411. Try `npm publish --registry <registry_url>` as a workaround.

Fix underway in #2445.

**Comment by manuelottlik** [comment]
I am publishing my npm packages to my private npm registry via GitHub Actions and had the same issue.

Am I correct that this currently effects **everyone** that uses `npm publish` in CI to a private registry?

**Comment by foxxyz** [comment]
> I am publishing my npm packages to my private npm registry via GitHub Actions and had the same issue.
> 
> Am I correct that this currently effects **everyone** that uses `npm publish` in CI to a private registry?

That's been my findings so far. I hope the CLI team fixes this quickly.

**Comment by mswaagman-godaddy** [comment]
https://github.com/npm/cli/pull/2445 did not fix it afaik. `publishConfig` seems to be ignored when publishing a package. Double checked if 7.5.3 would fix it, but does not appear to be the case.

**Comment by medianick** [comment]
Until a short while ago, I was seeing this very same issue with npm 7.5.1 when publishing to a private MyGet feed from our Jenkins system; despite a valid token in the `.npmrc` file it was still showing the `ENEEDAUTH` error and saying I needed to log in. @foxxyz's [workaround](https://github.com/npm/cli/issues/2453#issuecomment-757393140) of specifying the registry explicitly in the `npm publish` command resolved the problem. So, at least as of 7.5.1 the underlying issue has not been solved, and it sounds like 7.5.3 does not do so either, but at least our publishing can function again.

**Comment by linkej-autodesk** [comment]
We have the same problem with 7.5.4. using `--registry` did not fix it, unfortunately. I guess we'll stay at 6.x for now...

**Comment by grahaml** [comment]
FWIW using `--registry` as @medianick and @foxxyz mentioned has worked for me using GitLab's package registry. Just in case anyone else stumbles upon this thread and hasn't tried it yet. 

```
# .npmrc
@myscope:registry=https://gitlab.mycompany.com/api/v4/packages/npm/
//gitlab.mycompany.com/api/v4/packages/npm/:_authToken=<valid_access_token>
```

```
$ npm publish --regsitry=https://gitlab.mycompany.com/api/v4/packages/npm/
```

**Comment by avezina-ubik** [comment]
> We have the same problem with 7.5.4. using `--registry` did not fix it, unfortunately. I guess we'll stay at 6.x for now...

Same here using 7.6.0 and `gitlab.com` as private registry.

It seems that the publish command does not support a `--registry` argument though: https://docs.npmjs.com/cli/v7/commands/npm-publish

**Comment by foxxyz** [comment]
> It seems that the publish command does not support a `--registry` argument though: https://docs.npmjs.com/cli/v7/commands/npm-publish

I'd argue this should be documented better, but I believe the `--registry` argument is a global one that can be used on any `npm` command, as detailed in the [last paragraph under "Description" on the "registry" page](https://docs.npmjs.com/cli/v7/using-npm/registry).

**Comment by avezina-ubik** [comment]
> > It seems that the publish command does not support a `--registry` argument though: https://docs.npmjs.com/cli/v7/commands/npm-publish
> 
> I'd argue this should be documented better, but I believe the `--registry` argument is a global one that can be used on any `npm` command, as detailed in the [last paragraph under "Description" on the "registry" page](https://docs.npmjs.com/cli/v7/using-npm/registry).

It's a bit hard to understand indeed, but let's not start a debate about documentation.

I managed to get it published using npm 6.14.4 and the --registry flag.

**Comment by lolopinto** [comment]
when is this being fixed? I upgraded my npm from 6.* to 7.* and I'm running into this.

i'm trying to publish into a private github package. The suggestion to use `--registry` isn't working for me because I'm trying to publish a `dist` subfolder and apparently that combo together doesn't work.

**Comment by weaintplastic** [comment]
I;m using an artifactory registry and experience the same issue after upgrading npm v6 to v7. Looking forward to a fix to be able to upgrade to npm 7.

**Comment by midan888** [comment]
@weaintplastic same issue here, did you manage to use npm7 and artifactory publishing ?

**Comment by weaintplastic** [comment]
@midan888 Unfortunately not. We've opened a support ticket for the artifactory team and I suggest you do this as well.

**Comment by weaintplastic** [comment]
@midan888 it works using the legacy authentication method with a `_password` and `username` entry in the `.npmrc` file instead of `_auth`

**Comment by mrAnomalyy** [comment]
Still actual on `node@16.2.0, npm@7.16.0`

**Comment by Blackclaws** [comment]
Still an issue on npm@7.17.0 with gitlab

**Comment by ljharb** [comment]
What about npm v7.20.0?

**Comment by pjanuario** [comment]
> What about npm v7.20.0?

Still a issue, just stumbled on this and looking for a way to publish to gitlab.com.

on both combos:

```
 $ node -v
v16.0.0
 $ npm -v
7.20.0
```

```
 $ node -v
v16.5.0
 $ npm -v
7.20.1
```

**Comment by pjanuario** [comment]
Going to report my use case here and the attempts I did.

We are using gitlab.com as private registry, with the following versions:

```
 $ node -v
v16.5.0
 $ npm -v
7.20.1
```

I have configured a scoped package with the name format `org@my-package` and added the property publishConfig on the package json with the URI of the project.

```
{
  "name": "@org/my-package",
  "version": "0.0.1",
  "publishConfig": {
    "@org:registry": "https://gitlab.com/api/v4/projects/0000000/packages/npm/"
  }
}

```

When I use npm set config at the project level it works but when using the instance level it states adduser.

**Comment by BruneXX** [comment]
Hi Guys, I'm running 

npm -v 
7.20.3
node -v
v14.17.3

And I've the same issue, any workaround for that?

**Comment by calvinf** [comment]
I tried using npm v7 and npm v6 and couldn't get it to work.

I tried using `yarn publish` and it handled as expected. So while I'd rather not need `yarn` for this and it's something that `npm` should handle properly, I'm glad there's an alternative.

**Comment by lavcraft** [comment]
The same issue. I don't have idea for fix this, but it's look like a very annoying bug

**Comment by razzeee** [comment]
I had to change from 
```
npm publish dist
```

to

```
npm publish dist/
```

which somehow fixed this problem

**Comment by itchwoot** [comment]
We are having the same issue. node 16 will be the new active LTS version soon, so we would like to upgrade. Trying to publish to a private Gitlab registry using the node:16-buster Docker image gives us

```
npm ERR! need auth This command requires you to be logged in.
npm ERR! need auth You need to authorize this machine using `npm adduser`
```

node 16.9.1
npm 7.21.1

The `--registry` workaround suggested here doesn't work.

Everything worked fine with node 14.17.6 and npm 6.14.15

**Comment by sijakret** [comment]
~~still seeing this with npm `8.1.0` when trying to publish to a private registry~~

~~neither `.npmrc` nor `publishConfig` in package.json are being picked up~~

EDIT: It does work. I had a type in the registry url..

**Comment by gerhat** [comment]
Same issue with `npm v8.1.0` and Sonatype Nexus. Works fine with `npm v6.14.15`

**Comment by njefsky** [comment]
We also have this issue with npm 8.1.3
Unable to publish to Artifactory with the same error.
6.14.15 works.

**Comment by pfeileon** [comment]
This issue should not be lowest priority.
This means everyone who uses Artifactory, for instance, has to keep using node 14 with npm 6.

**Comment by bvallee-thefork** [comment]
Workaround for those having the same issue (if you don't need an auth token), in your `.npmrc`:

```
//your-private-npm-registry.your-company.com/:_authToken=npm_cli_issue_2453_workaround
```

([source](https://stackoverflow.com/a/66037808/581919))

**Comment by sijakret** [comment]
One thing i realized is that for some private registries (like azure dev ops)
when pushing packages, it is not enough to only authenticate the `.../npm/registry/` endpoint but also `.../npm/` in your .npmrc
i.e.
```
; for publishing this might ne be enough
//pkgs.dev.azure.com/.../_packaging/.../npm/registry/:username=[username]
//pkgs.dev.azure.com/.../_packaging/.../npm/registry/:_password=[pw]
//pkgs.dev.azure.com/.../_packaging/.../npm/registry/:email=..
; you might also need this:
//pkgs.dev.azure.com/.../_packaging/.../npm/:username=[username]
//pkgs.dev.azure.com/.../_packaging/.../npm/:_password=[pw]
//pkgs.dev.azure.com/.../_packaging/.../npm/:email=..
```

**Comment by njefsky** [comment]
both workarrounds above are not working for me.

We installed nvm and both 16.13.0 and 14.x node LTS versions with comes with npm 8.1.3  and 6.14.15.
install, lint, audit and build we do with 16.x
then nvm use 14.x
nvm publish
then nvm use 16.13.0 again to switch back to latest 

This works but is ofc far from a definite solution.
Please put this higher on the list.  It is an anoying bug.

**Comment by sysmat** [comment]
Any solution, also npm ver. 8 the same problem, is this braking changes? If so what is alternative?

**Comment by adjenks** [comment]
Everyone please upvote this issue, it's terrible and it completely destroys productivity.

**Comment by adjenks** [comment]
I'm encountering the same problem and the workarounds don't seem to work. I guess I'll roll back to version 6.

Update:
When I ran the adduser command in the latest version my `_auth` entry seemed to disappear from `.npmrc` and it added a login token line, but I could still not use publish.
After rolling back npm to version 6, re-adding my `_auth` entry, and then using `npm login --registry=http://nexus_url:port/repository/path` to log in, I was then finally able to publish. Not sure if `_auth` did anything, it didn't seem to work until I used the login command.

**Comment by rmainil** [comment]
Any update or news ?
I encounter the same problem with npm 8 / node 16. This prevent us to update and becomes really blocking.

**Comment by thasmo** [comment]
Experiencing the same with `npm@8` and private registries on gitlab.com.

**Comment by zadinvit** [comment]
npm version 8.1.0 upload to gitlab still not fixed

**Comment by jonathanmedd** [comment]
I have the same issue with npm 8.1.2 and Nexus

**Comment by beltekylevi** [comment]
tested with `node@14.16.1`, `npm@8.3.0`, and GitHub Packages

set publish registry in `package.json`
(I think this is replaceable with `npm publish --registry=https://npm.pkg.github.com/`)

```json
"publishConfig": {
  "registry": "https://npm.pkg.github.com/"
}
```

`.npmrc` content
```rc
//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}
always-auth=true
```

The `NODE_AUTH_TOKEN` environment variable must be set to a [GitHub PAT](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) with `write:packages` scope.

**Comment by dgr-m** [comment]
I checked the source code behind the `npm publish` command and it turns out that the only possible way to prevent this is to explicitly pass any credentials through the command line as arguments.
```javascript
if (!dryRun) {
  const resolved = npa.resolve(manifest.name, manifest.version)
  const registry = npmFetch.pickRegistry(resolved, opts)
  const creds = this.npm.config.getCredentialsByURI(registry)
  if (!creds.token && !creds.username) {
    throw Object.assign(new Error('This command requires you to be logged in.'), {
      code: 'ENEEDAUTH',
    })
  }
  await otplease(opts, opts => libpub(manifest, tarballData, opts))
}
```
The problem is in this line:
```javascript
const creds = this.npm.config.getCredentialsByURI(registry)
```
It checks the config for certain credential properties (eg. `_authToken`), but only the config from the cli. 
Defaults, user .npmrc, project .npmrc, etc are all ignored.

```javascript
getCredentialsByURI (uri) {
  const nerfed = nerfDart(uri)
  const creds = {}

  const email = this.get(`${nerfed}:email`) || this.get('email')
  if (email)
    creds.email = email

  const tokenReg = this.get(`${nerfed}:_authToken`) ||
    this.get(`${nerfed}:_authtoken`) ||
    this.get(`${nerfed}:-authtoken`) ||
    nerfed === nerfDart(this.get('registry')) && this.get('_authToken')
  
  ...
}

get (key, where) {
  if (!this.loaded)
    throw new Error('call config.load() before reading values')
  return this[_get](key, where)
}
// we need to get values sometimes, so use this internal one to do so
// while in the process of loading.
[_get] (key, where = null) {
  if (where !== null && !confTypes.has(where)) {
    throw new Error('invalid config location param: ' + where)
  }
  const { data, source } = this.data.get(where || 'cli')
  return where === null || hasOwnProperty(data, key) ? data[key] : undefined
}
```

Notice data is retrieved using the `where` arg (one of `default` `builtin` `global` `user` `project` `env` `cli`) which defaults to `cli` when none is provided (which is the case for `getCredentialsByURI`)

**Comment by sharkymcdongles** [comment]
> I checked the source code behind the `npm publish` command and it turns out that the only possible way to prevent this is to explicitly pass any credentials through the command line as arguments.
> 
> ```js
> if (!dryRun) {
>   const resolved = npa.resolve(manifest.name, manifest.version)
>   const registry = npmFetch.pickRegistry(resolved, opts)
>   const creds = this.npm.config.getCredentialsByURI(registry)
>   if (!creds.token && !creds.username) {
>     throw Object.assign(new Error('This command requires you to be logged in.'), {
>       code: 'ENEEDAUTH',
>     })
>   }
>   await otplease(opts, opts => libpub(manifest, tarballData, opts))
> }
> ```
> 
> The problem is in this line:
> 
> ```js
> const creds = this.npm.config.getCredentialsByURI(registry)
> ```
> 
> It checks the config for certain credential properties (eg. `_authToken`), but only the config from the cli. Defaults, user .npmrc, project .npmrc, etc are all ignored.
> 
> ```js
> getCredentialsByURI (uri) {
>   const nerfed = nerfDart(uri)
>   const creds = {}
> 
>   const email = this.get(`${nerfed}:email`) || this.get('email')
>   if (email)
>     creds.email = email
> 
>   const tokenReg = this.get(`${nerfed}:_authToken`) ||
>     this.get(`${nerfed}:_authtoken`) ||
>     this.get(`${nerfed}:-authtoken`) ||
>     nerfed === nerfDart(this.get('registry')) && this.get('_authToken')
>   
>   ...
> }
> 
> get (key, where) {
>   if (!this.loaded)
>     throw new Error('call config.load() before reading values')
>   return this[_get](key, where)
> }
> // we need to get values sometimes, so use this internal one to do so
> // while in the process of loading.
> [_get] (key, where = null) {
>   if (where !== null && !confTypes.has(where)) {
>     throw new Error('invalid config location param: ' + where)
>   }
>   const { data, source } = this.data.get(where || 'cli')
>   return where === null || hasOwnProperty(data, key) ? data[key] : undefined
> }
> ```
> 
> Notice data is retrieved using the `where` arg (one of `default` `builtin` `global` `user` `project` `env` `cli`) which defaults to `cli` when none is provided (which is the case for `getCredentialsByURI`)

Can you give an example of what the npm publish command would look like when passing auth as arguments? I don't see this documented anywhere at all.

**Comment by coroiu** [comment]
I had this issue on Gitlab with node 16.4.2 and npm 7.18.1 and solved it by pointing to the `.npmrc` using `npm publish --userconfig [.npmrc path]`. No need to point out the registry directly

**Comment by radoslawgrochowski** [comment]
@coroiu Could you share your `.npmrc`?

**Comment by NiklasPor** [comment]
This one is also stopping us from publishing with Node 16. We just switched to a Node 14 image for our publish pipeline step.

**Comment by jonathaff** [comment]
@radoslawgrochowski I followed @coroiu tip and it works for me, nexus 3.37, gitlab 14.6, node 16.13 and npm 8.1. Here is my setup:

~/.npmrc content, created after read this thread https://clavinjune.dev/en/blogs/npm-login-not-working/

```
registry=https://nexus.my.repo/repository/npm-all-releases
//nexus.my.repo/repository/internal-npm-releases/:_auth={{ base64 of username:password redacted here }}
```

Publish command
`npm publish --userconfig=~/.npmrc --registry=https://nexus.my.repo/repository/internal-npm-releases/`

**Comment by moha-akb** [comment]
Same problem for me.
Tried most of solutions, and finally this worked for me:

(Not logged in globaly)
./.npmrc
```
registry="https://npm.pkg.github.com/"
//npm.pkg.github.com/:_authToken=YOUR_AUTH_TOKEN
save-exact=true
```
run command:
`npm publish --regsitry=https://npm.pkg.github.com/ --userconfig=./.npmrc`


Note: for the most of the failed tries, `registry=...` was missing in `.npmrc`

**Comment by ghost** [comment]
This is still an issue with node v16.14.0 and npm v8.3.1. Worked fine with node 14.x and npm 5.x.

**Comment by ljharb** [comment]
@budgecode what about npm v8.5.1?

**Comment by radoslawgrochowski** [comment]
> @radoslawgrochowski I followed @coroiu tip and it works for me, nexus 3.37, gitlab 14.6, node 16.13 and npm 8.1. Here is my setup:
> 
> ~/.npmrc content, created after read this thread https://clavinjune.dev/en/blogs/npm-login-not-working/
> 
> ```
> registry=https://nexus.my.repo/repository/npm-all-releases
> //nexus.my.repo/repository/internal-npm-releases/:_auth={{ base64 of username:password redacted here }}
> ```
> 
> Publish command `npm publish --userconfig=~/.npmrc --registry=https://nexus.my.repo/repository/internal-npm-releases/`

Thanks, first solution that works for me :)

**Comment by wickkidd** [comment]
+1 on it working when using `registry` and `userconfig` cli args. Like others, I didn't have to change my `.npmrc` from the format I used prior to npm v8. That said, the only thing I actually had to change was to pass the the `userconfig` arg.

**Comment by wraithgar** [comment]
It does look like this was due to configuration changes in npm7/8.  publishConfig is being properly applied during publishes, and registry and scope-specific configs are working as expected in the latest npm.

If folks are still experiencing issues publishing to private registries, please open individual tickets so that we can triage and debug your specific config setup.

**Comment by pfeileon** [comment]
> I checked the source code behind the `npm publish` command and it turns out that the only possible way to prevent this is to explicitly pass any credentials through the command line as arguments.
> 
> ```js
> if (!dryRun) {
>   const resolved = npa.resolve(manifest.name, manifest.version)
>   const registry = npmFetch.pickRegistry(resolved, opts)
>   const creds = this.npm.config.getCredentialsByURI(registry)
>   if (!creds.token && !creds.username) {
>     throw Object.assign(new Error('This command requires you to be logged in.'), {
>       code: 'ENEEDAUTH',
>     })
>   }
>   await otplease(opts, opts => libpub(manifest, tarballData, opts))
> }
> ```
> 
> The problem is in this line:
> 
> ```js
> const creds = this.npm.config.getCredentialsByURI(registry)
> ```
> 
> It checks the config for certain credential properties (eg. `_authToken`), but only the config from the cli. Defaults, user .npmrc, project .npmrc, etc are all ignored.
> 
> ```js
> getCredentialsByURI (uri) {
>   const nerfed = nerfDart(uri)
>   const creds = {}
> 
>   const email = this.get(`${nerfed}:email`) || this.get('email')
>   if (email)
>     creds.email = email
> 
>   const tokenReg = this.get(`${nerfed}:_authToken`) ||
>     this.get(`${nerfed}:_authtoken`) ||
>     this.get(`${nerfed}:-authtoken`) ||
>     nerfed === nerfDart(this.get('registry')) && this.get('_authToken')
>   
>   ...
> }
> 
> get (key, where) {
>   if (!this.loaded)
>     throw new Error('call config.load() before reading values')
>   return this[_get](key, where)
> }
> // we need to get values sometimes, so use this internal one to do so
> // while in the process of loading.
> [_get] (key, where = null) {
>   if (where !== null && !confTypes.has(where)) {
>     throw new Error('invalid config location param: ' + where)
>   }
>   const { data, source } = this.data.get(where || 'cli')
>   return where === null || hasOwnProperty(data, key) ? data[key] : undefined
> }
> ```
> 
> Notice data is retrieved using the `where` arg (one of `default` `builtin` `global` `user` `project` `env` `cli`) which defaults to `cli` when none is provided (which is the case for `getCredentialsByURI`)

@wraithgar So this is now called a configuration change?

Sounds like manager talk to me: After more than a year people have found workarounds or learned to live with version 6 anyway, just close the issue and let them file an issue for their "individual" problem, which most won't do or only do after another few months. 👎

**Comment by wraithgar** [comment]
I'm sorry that you feel this way, but the issue here originally was that publishConfig was not being properly applied during publish. That has been fixed.  It is very likely you either have a separate issue or a config mismatch.  The new issue template is designed to help us triage and debug these things.  Comments in a closed issue are generally not a good place for that.

As for the config, the data objects are cumulative.  The internal [_get] only limits to the `where` if it was requested.  Otherwise it returns the value

```
return where === null || hasOwnProperty(data, key) ? data[key] : undefined
```

`config.get('sign-git-tag')` will return the config value as it was derived and set through all of the various config locations.  `config.get('sign-git-tag', 'cli')` will return the config value as it was set on cli parameters.  If you don't give a `where`, it pulls from the *internal* cli data object, which includes the total data of the config.  The internal data has all of the config items in it as non-enumerable properties.  This is how the config works under the hood.  That's how you can see things like this if you look at it in a repl

```
> config.data.get('cli').data
Object <Object <Object <Object <Complex prototype>>>> {}
> Object.hasOwnProperty(config.data.get('cli'), 'sign-git-tag')
false
> config.data.get('cli').data['sign-git-tag']
true
```

This is not an attempt at ignoring the issue. If there is a bug we really do want to fix it.  Please do open new issues and fill out the information requested so we can properly triage it.

**Comment by pfeileon** [comment]
So what you're saying is that @sysmat 's issue is resolved?
Because from my understanding authentication still doesn't work without changing the CLI command which might be out of reach if you use semantic-release or similar.

**Comment by wraithgar** [comment]
Yes their issue is resolved.  publishConfig with a nerfed `_authToken` works and has tests.  The other issue appears to be with scoped registries and the old `_auth` token which has another open issue that is being worked on now https://github.com/npm/cli/issues/3573

This is why it's so important to have separate issues for things.  I know that on the surface these all feel like the same issue but they're not, and mixing them up in the comments slows down the debugging and triage process.

We really are doing our best to fix issues, and the things we're asking for are in the interest of getting bugs fixed, I promise.  Thank you for your attention to these issues and please continue to try to debug, and open issues if there are new bugs.

**Comment by asotog** [comment]
Hi all,

I'm still experiencing this issue when running `npm publish`:
```
npm notice 
npm ERR! code ENEEDAUTH
npm ERR! need auth This command requires you to be logged in to MY_PRIVATE_NEXUS_REGISTRY_URL
npm ERR! need auth You need to authorize this machine using `npm adduser`

npm ERR! A complete log of this run can be found in:

node -v
v16.14.1
npm -v
8.5.0
```

I spent whole afternoon until I go to a lower version, in my case I tried node 12, node v12.22.9 (npm v6.14.15), and it worked again

**Comment by asotog** [comment]
Just found this command:
```
 npm adduser --registry=REGISTRY_URL
```
and use the right user, then was complaining about other information related to nexus which this helped me https://blog.katastros.com/a?ID=01750-614d5a39-d787-4987-89bb-0b2f03210e1f

**Comment by matthias-ccri** [comment]
Coming here from npm `8.15.1` using `beachball`. It turns out there was a discrepancy between the configurations --- a trailing slash. This discrepancy only produced an error starting in npm `7.3.0`. In `7.2.0` and before, npm worked.

In `beachball.config.js` the registry lacked a trailing slash, but in the CI job's `npm config registry` command, there was a trailing slash. As a result `beachball` issued a command without the trailing slash (the command is visible in the job output), and npm threw a `ENEEDAUTH`.

Note: the `ENEEDAUTH` is not from the server; it's from npm itself, when npm thinks it needs auth info, but can't find it.

**Comment by adjenks** [comment]
> Just found this command:
> 
> ```
>  npm adduser --registry=REGISTRY_URL
> ```
> 
> and use the right user, then was complaining about other information related to nexus which this helped me https://blog.katastros.com/a?ID=01750-614d5a39-d787-4987-89bb-0b2f03210e1f

I was using nexus and your link saved me. This is what got me:
> If you still can’t send after logging in, check the Realms setting of npm nexus, put npm Bearer Token Reaim into Active, and save

I couldn't imagine that nexus would not have that on by default so I never thought to check.

**Comment by l3ender** [comment]
Though not directly related to the `adduser` issue, I stumbled on this post facing `npm publish` issues after updating to node 16 (npm 8.19.3). I'm posting here as it may help someone else.

We build our library and then publish as follows:

```bash
-> npm publish dist/my-library

npm ERR! code 128
npm ERR! An unknown git error occurred
npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/dist/my-library.git
npm ERR! ERROR: Repository not found.
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
```

After updating to node 16, it appears the trailing slash on the path is required. Without it, npm tries to use an SSH URL, as observed in the failed output.

The solution was to use the path with a trailing slash:

```bash
npm publish dist/my-library/
```
