### ISSUE TITLE
[BUG] Cannot read property 'pickAlgorithm' of null

### ISSUE THREAD

**Issue by stevenobadiah** [npm/cli#3374]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Whenever typing an npx function, I receive an error. It seems that NPM, itself, is broken on my device.

When typing npx create-react-app testing in my terminal, I receive the following error:
Invalid response body while trying to fetch https://registry.npmjs.org/create-react-app: Cannot read property 'pickAlgorithm' of null

Which produces the below error log:
[2021-06-06T03_09_42_989Z-debug.log](https://github.com/npm/cli/files/6603592/2021-06-06T03_09_42_989Z-debug.log)

### Expected Behavior

I was not expecting an error to occur. I was expecting an application to be created.

### Steps To Reproduce

1. In this environment...
I am on Ubuntu and typing into my terminal. I was attempting to install jest for testing in a react project, and I accidentally typed "npm install --save-dev jes" instead (notice the missing t). I aborted that command a few seconds after my terminal started logging changes, and my npm has been broken since.

2. With this config...
This problem isn't specific to any project - it is an issue across my entire directory.

3. Run '...'
As stated, I originally ran  "npm install --save-dev jes".

Afterwards, when I tried creating the testing application, which resulted in my terminal spewing countless lines of errors before telling me that I should log this issue.

I then tried to create my testing application again, but this time I received an error stating I don't have enough space on my device, which made me think that the prior error consumed space on my device. I checked my storage with df -h, and I saw that my /dev/sdal, /dev/loop0, and /dev/loop1 folders were all full. I cleared my trash folder, and then I ran npm cache clean --force to try and lower the storage, but only /dev/sdal went down (and only to 90%).

4. See error...
Now when I try to create my testing application, the error I see is as the one in my Current Behavior description. 
Invalid response body while trying to fetch https://registry.npmjs.org/create-react-app: Cannot read property 'pickAlgorithm' of null

### Environment

- OS: Ubuntu 20.04
- Node: v14.1.0
- npm: 7.16.0

**Comment by I057542** [comment]
Hi @stevenobadiah , 
how was this issue be resolved?  unfortunately I encountered a similar issue. 
my environment is: 

- Node: v12.18.4
- npm: 7.19.0

thank you!
BR, Eva

**Comment by stevenobadiah** [comment]
Hi,

I updated my virtual machine and the problem fixed itself. Unfortunately, I
don't have much to report beyond that :/

Good luck!

Steven

**Comment by I057542** [comment]
Hi @stevenobadiah 
thank you for your response. it seems "Good Luck!" is very useful ;)

my issue was also resolved, instead of upgrade my laptop (... this is too risky.. )
I saw a blog and follow the guides to clear npm cache, and then execute installation successfully. 
the command is, 

> npm cache clear --force
> npm i -g @sap/cds-dk

Best Regards,
Eva

**Comment by siluski** [comment]
Good afternoon all, this still seems to persist as an issue. Myself and others still seem to be running into this problem, as you can see here in a question posed just a week ago : https://answers.sap.com/questions/13610872/how-to-resolve-this-npm-err-cannot-read-property-p.html. I'm currently trying to fix dependency issues in my package.json in a CAP application, and when I attempt to do so I encounter the error : ERR! Cannot read property 'pickAlgorithm' of null. I've attempted clearing the cache, and running it fresh, still encounter the same problem. I am using SAP BAS, and my npm version is 7.24.2. The full details of the attempt to fix all dependencies are below. 

[4:45:29 PM] Fixing dependency issues...

npm
 notice Beginning October 4, 2021, all connections to the npm registry - including for package installation - must use TLS 1.2 or higher. You are currently using plaintext http to connect. Please visit the GitHub blog for more information: https://github.blog/2021-08-23-npm-registry-deprecating-tls-1-0-tls-1-1/

npm
 notice Beginning October 4, 2021, all connections to the npm registry - including for package installation - must use TLS 1.2 or higher. You are currently using plaintext http to connect. Please visit the GitHub blog for more information: https://github.blog/2021-08-23-npm-registry-deprecating-tls-1-0-tls-1-1/

npm
 WARN deprecated har-validator@5.1.5: this library is no longer supported

npm 
WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

npm WARN 
deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

npm
 WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future

npm
 
WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.

npm
 
ERR! Cannot read property 'pickAlgorithm' of null



npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2022-04-08T16_46_01_150Z-debug.log

I created a fresh application, to make sure that it's not unique to one particular app, and the same issue occurs. Any assistance would be greatly appreciated.

**Comment by sanjoy0308** [comment]
I also faced same issue. I tried lot of the things suggested here and there and nothing worked. Then I pushed code to git and deleted the space and cloned again in new space. Problem is gone.

**Comment by peter** [comment]
I ran into the same problem now when doing `npm install -g mongodb-realm-cli` on Node `v16.13.1`:

299 verbose stack TypeError: Cannot read properties of null (reading 'pickAlgorithm')
299 verbose stack     at Integrity.match (/Users/peter/.nvm/versions/node/v16.13.1/lib/node_modules/npm/node_modules/ssri/index.js:234:24)
299 verbose stack     at CachePolicy.satisfies (/Users/peter/.nvm/versions/node/v16.13.1/lib/node_modules/npm/node_modules/make-fetch-happen/lib/cache/policy.js:113:49)
299 verbose stack     at Function.find (/Users/peter/.nvm/versions/node/v16.13.1/lib/node_modules/npm/node_modules/make-fetch-happen/lib/cache/entry.js:172:25)
299 verbose stack     at async cacheFetch (/Users/peter/.nvm/versions/node/v16.13.1/lib/node_modules/npm/node_modules/make-fetch-happen/lib/cache/index.js:8:17)
299 verbose stack     at async fetch (/Users/peter/.nvm/versions/node/v16.13.1/lib/node_modules/npm/node_modules/make-fetch-happen/lib/fetch.js:82:7)
300 verbose cwd /Users/peter/src/acast/open
301 verbose Darwin 20.3.0
302 verbose argv "/Users/peter/.nvm/versions/node/v16.13.1/bin/node" "/Users/peter/.nvm/versions/node/v16.13.1/bin/npm" "install" "-g" "mongodb-realm-cli"
303 verbose node v16.13.1
304 verbose npm  v8.1.2
305 error Cannot read properties of null (reading 'pickAlgorithm')
306 verbose exit 1

**Comment by PaulVipond** [comment]
This keeps on happening to me and clearing the cache is painful because all of your globally installed packages disappear. So I did some digging. The issue for me appears in the 'make-fetch-happen' module:

```  
  // returns true if the policy satisfies the request
  satisfies (request) {
     ...
    if (this.options.integrity) {
      return ssri.parse(this.options.integrity).match(this.entry.integrity)
    }
  }
```
In my case, this.options has an integrity property, but this.entry doesn't. So either here, or further down in the call-stack (SSRI module Integrity.match ssri\lib\index.js:273:24), there needs to be a check for either the fetched entry or the cache entry having no integrity property. Unless that's obviously some kind of fundamental error and plainly shouldn't happen:

```
  match (integrity, opts) {
    opts = ssriOpts(opts)
    const other = parse(integrity, opts)
    const algo = other.pickAlgorithm(opts)      <--- fails here as integrity is null on entering the function
    return (
      this[algo] &&
      other[algo] &&
      this[algo].find(hash =>
        other[algo].find(otherhash =>
          hash.digest === otherhash.digest
        )
      )
    ) || false
  }

```

**Comment by PaulVipond** [comment]
Anyone reaching here and wanting a sanity saving, but very hacky, completely unsupported and use at your own risk workaround. Edit ssri\lib\index.js in your global npm cache and add the following to the match() function (currently line 270):
```
  match (integrity, opts) {
    if (integrity == null)
      return false;
```
That allowed my NPM install to finish. I also raised the issue with more debug detail here: https://github.com/npm/ssri/issues/27

**Comment by ljharb** [comment]
@PaulVipond clearing the cache has no impact on your global modules; they’re not stored in the same place.

**Comment by gcrozariol** [comment]
> 

npm cache clear --force really worked for me! Thanks :)

**Comment by bch15** [comment]
This steps worked for me:
```
npm cache clear --force
npm config set registry https://registry.npmjs.org

```

**Comment by Josephkagimu1** [comment]
I ran **npm update**  and my issue was solved .

**Comment by hrhm47** [comment]
i ran **npm update** in my _project cmd_ issue was solved 
**@Josephkagimu1**  thank you for comment it also resolved my problem.

**Comment by Webbrother** [comment]
```
➜  node -v
v16.15.0
➜  npm -v
8.18.0
```

I got `npm ERR! Cannot read properties of null (reading 'pickAlgorithm')` error after every `npm install`.

**Comment by wrongbyte** [comment]
Why is this issue marked as closed? It seems that this error keeps happening and, although the recommended solution is to clean the cache, the real root of the problem remains unclear.

**Comment by OmgImAlexis** [comment]
Just hit this in a github actions workflow. ~~Re-running the job fixed it~~(or so I thought, nope same issue.) but the root cause still seems to be there.

Using `node@18.3.0` not sure on the npm version.

**Comment by ling1115** [comment]
Hi, i had meet the same problem NOW. 
and i try to resolve it by `npm cache clear --force` or `npm config set registry https://registry.npmjs.org/`.
but it doesn't work for me.
and then i try to fixed it by **`npm update`**.
and it has worked.
hope to help you. 
good luck.

environment：
node: v16.13.0
npm: 8.1.4
sys: macOS Monterey 12.5

chen

**Comment by DetachHead** [comment]
@stevenobadiah can you please re-open this? i have to run `npm cache clean --force` every time i do an `npm install` to avoid this error, so this is still an issue.

**Comment by OmgImAlexis** [comment]
Been hitting this on almost every single install today. Just as @DetachHead said above, I'm having to clear the cache before `npm i` will work. It then only works once before needing to run it again. 😞 

Is this possibly an issue with the connection to npm being flaky?

**Comment by DetachHead** [comment]
> Is this possibly an issue with the connection to npm being flaky?

potentially, this only happens on my work PC which is connecting to npm from behind an authenticated proxy. perhaps that's related? #3810

**Comment by OmgImAlexis** [comment]
I'm using npm without any proxy. Not sure what to try at this point as cache clearing doesn't seem to be fixing it.

```
npm ERR! code 1
npm ERR! git dep preparation failed
npm ERR! command /usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/root/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm ERR! Cannot read properties of null (reading 'pickAlgorithm')
npm ERR!
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /root/.npm/_logs/2022-09-13T06_10_48_215Z-debug-0.log

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-09-13T06_09_37_059Z-debug-0.log
```

Something I noticed is the log file it mentions is always empty.

**Comment by williams8299** [comment]
This is still an isuue

**Comment by aliwahab1** [comment]
Thanks, Alien(programmer) npm cache clear --force work for me. God bless you all

**Comment by rodrigobertolottizinsp** [comment]
Anyone know why this is happening? It always has been pretty straightforward to install packages and this seems to be happening to a lot of people..

**Comment by Tellys** [comment]
The article below answered your question well. Pickalgorithm npm error

[https://www.conteudopertinente.com.br/npm/pickalgorithm-npm-error/](https://www.conteudopertinente.com.br/npm/pickalgorithm-npm-error/)
