### ISSUE TITLE
 npm ERR! Unexpected token '.' 

### ISSUE THREAD

**Issue by syedbilal07** [npm/cli#4303]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I have updated to the latest npm v8.3.2 and it is showing me an error while using the command "npm install". What is the solution?
Please see my previous issue: https://github.com/npm/cli/issues/4234 (same was present in v8.3.1). I don't want to switch my nodejs to LTS release

### Expected Behavior

It should install the required package

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...
I am using Windows 10 (Enterprise - Latest Version). I have the latest node and npm installed at the moment.

### Environment

- npm:
- Node.js:
- OS Name:
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```
; "user" config from C:\Users\Bilal.npmrc

registry = "http://registry.npmjs.org/"

; node bin location = C:\Program Files\nodejs\node.exe
; cwd = C:\Users\Bilal
; HOME = C:\Users\Bilal
; Run npm config ls -l to show all defaults.

**Comment by bonesoul** [comment]
+1

**Comment by vangop** [comment]
literally unusable

**Comment by bonesoul** [comment]
same here,

**Comment by MrGriefs** [comment]
Seems to be a change with Node 17.4.0 causing this break, works fine on 17.3.1 otherwise. I personally blame Gabe

**Comment by ruyadorno** [comment]
hi @syedbilal07 I'll close this issue in favor of keeping the conversation over at https://github.com/npm/cli/issues/4234, thanks!

**Comment by syedbilal07** [comment]
Ok sure.

**Comment by lanseliuyiya** [comment]
+1

**Comment by Codeway-js** [comment]
+1

**Comment by ghost** [comment]
With npm 8.5.0 and node 16.14.2 on windows I have the same issue tryign to clone a repo

**Comment by mathiasmaerker** [comment]
for me every `npm i-g ..` command fails with the same error message on Win 10

**Comment by thecassion** [comment]
I  have also the same problem

**Comment by HugoVersiani** [comment]
i have also the same problem

**Comment by lizaemran** [comment]
I also have same problem

**Comment by barunp** [comment]
I am also facing same problem in npm version 8.5.5 and nvm -v

Running version 1.1.7.

**Comment by olignyf** [comment]
Just a heads up, this has been fixed in nvm 1.1.10. 
Just install nvm 1.1.10 and you can use any newer node version without this error.
https://github.com/coreybutler/nvm-windows/releases

**Comment by talsunravi** [comment]
**npm ERR! Unexpected token '.'**

$ npm -v
8.19.2

$ nvm version
1.1.10

$ node -v
v16.18.1

$ npm i
npm ERR! Unexpected token '.'

**Comment by Tapudp** [comment]
Why has this been closed? 
I'm still facing this

```
(D:\work) =>  npm -v
8.6.0

(D:\work) =>  node -v
v18.0.0
```

I'm on windows 11.
