### ISSUE TITLE
[BUG] Invalid peer dependency resolution - unable to resolve dependency tree

### ISSUE THREAD

**Issue by moroine** [npm/cli#5055]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Fails to resolve `peerDependencies` when different packages are trying to request the following versions:
- `>=16.8.0`
- `^16.3.0 || ^17.0.2`

I have a package with the following shape:

```
{
   "name": "@nugit/csv-service-client",
   "peerDependencies": {
       "@chakra-ui/icons": "1.1.6",
       "@chakra-ui/react": "1.8.8",
       "@chakra-ui/system": "1.12.1",
       "@nugit/types": "^3.7.0",
       "react": "^16.13.1"
    }
}
```

```
{
   "name": "@nugit/types",
   "peerDependencies": {
       "react": "^16.13.1 || ^17.0.2"
    }
}
```

### Expected Behavior

Should resolve to `^16.8.0`

### Steps To Reproduce

[eresolve-report.txt](https://github.com/npm/cli/files/8957419/eresolve-report.txt)

### Environment

- npm: 8.12.2
- Node.js: 16.14.1
- OS Name: macOs Monterey
- System Model Name: Macbook Pro
- npm config:
```ini
; "user" config from /Users/moroine/.npmrc

; //registry.npmjs.org/:_authToken = (protected) ; overridden by project

; "project" config from /Users/moroine/Workspace/Nugit/csv-service/.npmrc

//registry.npmjs.org/:_authToken = (protected)

; node bin location = /usr/local/bin/node
; node version = v16.14.1
; npm local prefix = /Users/moroine/Workspace/Nugit/csv-service
; npm version = 8.12.2
; cwd = /Users/moroine/Workspace/Nugit/csv-service
; HOME = /Users/moroine
; Run `npm config ls -l` to show all defaults.
```

**Comment by estani** [comment]
I can reproduce this too. Updated to npm 8.13.1 but the error is still there:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: react-native-heic-converter@1.3.0
npm ERR! Found: react-native@0.63.4
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.63.4" from the root project
npm ERR!   peer react-native@">=0.63.0" from @codler/react-native-keyboard-aware-scroll-view@1.0.1
npm ERR!   node_modules/@codler/react-native-keyboard-aware-scroll-view
npm ERR!     @codler/react-native-keyboard-aware-scroll-view@"1.0.1" from native-base@2.15.2
npm ERR!     node_modules/native-base
npm ERR!       native-base@"^2.13.12" from @comjoo/ui-kit-mobile@1.2.0
npm ERR!       node_modules/@comjoo/ui-kit-mobile
npm ERR!         @comjoo/ui-kit-mobile@"^1.2.0" from the root project
npm ERR!   42 more (@comjoo/easy-core, react-native-image-crop-picker, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react-native@"^0.41.2" from react-native-heic-converter@1.3.0
npm ERR! node_modules/react-native-heic-converter
npm ERR!   react-native-heic-converter@"^1.3.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: react-native@0.41.2
npm ERR! node_modules/react-native
npm ERR!   peer react-native@"^0.41.2" from react-native-heic-converter@1.3.0
npm ERR!   node_modules/react-native-heic-converter
npm ERR!     react-native-heic-converter@"^1.3.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
```

I had to downgrade it  to 7.0.0 for this to go through (tried many options in between).
After resolution "works" I could increase the npm version back again to 8.5.5, v8.6.0 break it again.

So I guess the workaround is to downgrade to 8.5.5 and delete the `package-lock.json` (probably the reason I had to go the first time all the way to 7.0.0)
```
npm install -g npm@8.5.5
```

There are almost 300 files modified between those 2 versions so is very hard to see what could have gone wrong: https://github.com/npm/cli/compare/v8.5.5...v8.6.0

**Comment by ghost** [comment]
Having exactly the same issue, experiencing both on `8.11.0` and `8.13.1`

**Comment by fritzy** [comment]
I have the same resolution problem with `npm@8.5.5`.

We fixed inconsistencies between package-lock and package.json in npm@8.6.0, so you may need to clear it.
In this particular case, `react-dom` needs to be a (peer) dependency, because it's getting set to v18 instead v16, and then the peer deps for react cannot get resolved.

**Comment by ghost** [comment]
@fritzy clearing the package-lock was the first thing I did, and react-dom is one of our deps. This did not solve the issue for me.

**Comment by estani** [comment]
This is getting stranger... this is the minimal test I could do that shows in my case that starting from scratch 6.14.17 works, 7.0.0 do not.

I definitely got it working with at least 7.0.0 before, so this is some kind of a race condition as apparently the order of the entries are not stabilised before processing...

here a test I did:
```sh
perform_test() {
  (
  local v="$1"
  local dir="test_$v"
  npm i -g npm@$v
  mkdir "$dir" && cd "$dir" && npm init -y
  npm add react-native@0.63.4

  echo -e "\n\nOK now the real test starts..." && sleep 1
  if npm add react-native-heic-converter 
  then 
    echo -e "\n$v"' is Ok!'
  else
    echo -e "\n$v"' FAILED!!!!'
  fi
  )
}

perform_test 6.14.17  # works
perform_test 7.0.0    # breaks
```

tested in node v16.15.1 with zsh 5.8.1 (x86_64-apple-darwin21.0) and GNU bash, version 3.2.57(1)-release (arm64-apple-darwin21)

6.14.17 works always, 7.0.0 fails always.

**Comment by moroine** [comment]
@fritzy I don't think `react-dom` should be added as peer manually. In none of the packages, I use directly `react-dom` and it's not needed for the package. Why would I need to add it then?

If `react-dom` is peer dependency of `react` wouldn't `npm` be able to figure it out?

**Comment by estani** [comment]
@fritzy @moroine please open a new issue if you want to keep your discussion. There is no `react-dom` mentioned here, my test also don't include it (plain `react-native`) and this problem is much larger than one particular package, as the test shows. Otherwise you are driving the attention away from the problem in this thread. thanks!

**Comment by moroine** [comment]
Yeah, I agree this `react-dom` was just to mention an example. I still think this issue is valid and shouldn't be closed

**Comment by moroine** [comment]
@fritzy I think we should open this back as removing the lock file is not a good approach I think otherwise, what would be the reason to have a lock file if we need to remove it everytime 🤔
