### ISSUE TITLE
[BUG] v8.13.0 npm run <script> fails

### ISSUE THREAD

**Issue by JonasSchubert** [npm/cli#5066]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I am unable to run scripts defined in my package.json. `npm run <script>` outputs `The filename, directory name, or volume label syntax is incorrect.` (translated from german 'Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch.')
Downgrading to v8.12.2 for now as scripts are able to run using this npm version.

### Expected Behavior

All scripts should run without an error.

### Steps To Reproduce

1. Install the latest npm version 8.13.0 globally
2. Run any script defined in your package.json
4. See error: `The filename, directory name, or volume label syntax is incorrect.` (translated from german 'Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch.')

### Environment

- npm: 8.13.0
- Node.js: 16.15.1
- OS Name: Windows 10
- System Model Name: HP ZBook
- npm config:
```ini
; "builtin" config from C:\Users\[retracted]\AppData\Roaming\npm\node_modules\npm\npmrc

prefix = "C:\\Users\\[retracted]\\AppData\\Roaming\\npm"

; "user" config from C:\Users\[retracted]\.npmrc

[retracted]:registry = "[retracted]"
[retracted]:registry = "[retracted]"
[retracted]
registry = "[retracted]"

; node bin location = C:\Program Files\nodejs\node.exe
; node version = v16.15.1
; npm local prefix = [retracted]
; npm version = 8.13.0
; cwd = [retracted]
; HOME = C:\Users\[retracted]
; Run `npm config ls -l` to show all defaults.
```

**Comment by schachafatzitz** [comment]
i encountered the same issue

on my side i am running "npm run build"

the package.config contains these values

```
"build": "npm run legacy:build & nx build --prod  & nx build management --prod",
"legacy:build": "npm run build --prefix _legacy/",
```

when i change the colon into a dash everything works
```
"build": "npm run legacy-build & nx build --prod  & nx build management --prod",
"legacy-build": "npm run build --prefix _legacy/",
```

**Comment by nlf** [comment]
sorry about that one, folks. the pull request linked above should fix the issue for you and we'll get that out in a new npm release soon

**Comment by JonasSchubert** [comment]
Hi @nlf, I just installed npm@8.13.1 and I still encounter the failing scripts.
As @schachafatzitz described it is related to scripts with a colon, e.g. `build:prod` fails, but `build-prod` is ok.

Do we need to escape colons too, similar to spaces in your mentioned MR?

> i encountered the same issue
> 
> on my side i am running "npm run build"
> 
> the package.config contains these values
> 
> ```
> "build": "npm run legacy:build & nx build --prod  & nx build management --prod",
> "legacy:build": "npm run build --prefix _legacy/",
> ```
> 
> when i change the colon into a dash everything works
> 
> ```
> "build": "npm run legacy-build & nx build --prod  & nx build management --prod",
> "legacy-build": "npm run build --prefix _legacy/",
> ```

**Comment by Blodwynn** [comment]
Same here, we ended up downgrading to a previous npm version. 8.13.1 didn't fix the problem for us either.

**Comment by unpunnyfuns** [comment]
Same here, this ticket should probably be re-opened.

**Comment by BleedingDev** [comment]
Reproduced it too, downgrade to version 8.12.2 helped. :)

**Comment by frederikhors** [comment]
THIS IS HUGE!

**Comment by nlf** [comment]
this got closed when the dependency was updated, when #5086 here lands and is published in a couple of days the new release takes care of the issue with `:` in script names

**Comment by JoshMcCullough** [comment]
I hope the fix will also work when a script name contains slashes e.g. `build-spec:some/branch`.

**Comment by JonasSchubert** [comment]
> this got closed when the dependency was updated, when #5086 here lands and is published in a couple of days the new release takes care of the issue with `:` in script names

Thanks @nlf and all other contributors to npm. Your work is very much appreciated!
