### ISSUE TITLE
[BUG] presence of `overrides` breaks ability to update un-hoisted workspace dependencies

### ISSUE THREAD

**Issue by jenseng** [npm/cli#7018]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

If the root `package.json` defines **_any_** `overrides`, if you attempt to update an un-hoisted dependency by editing the workspace's `package.json` and then running `npm install`, the new version doesn't actually get installed.

Critically, `package-lock.json` **_does_** get updated when you do this, which may lead you to believe the new version was installed, but the old version still remains. This version mismatch can be detected by running `npm ls` (you'll get `ELSPROBLEMS`).

This has some similarities to #5850 -- in particular see [this comment](https://github.com/npm/cli/issues/4232#issuecomment-1034240038) on an earlier issue which describes the same `package-lock.json` discrepancy -- but the key difference here is that the actual overrides don't matter, this issue is about the (mis)behavior of un-hoisted dependency resolution.

### Expected Behavior

Editing a workspace's `package.json` and running `npm install` from the root should install the desired version(s) of dependencies, just as it does when you don't have any `overrides`.

Alternatively, `npm install` could detect the `package.json` <-> `package-lock.json` mismatch and tell the user to instead update the dependency via something like `npm install <specifier> --save-exact -w <workspace>`

Either solution would be vastly preferable to the current behavior where it appears to install the new version but actually keeps using the old one.

### Steps To Reproduce

Given `package.json`:

```json
{
  "workspaces": [
    "packages/*"
  ],
  "overrides": {
    "doesnt-matter-can-be-anything": "1.2.3"
  }
}
```

And `packages/my-cool-package/package.json`:
```json
{}
```

Run:
1. `npm i tiny-invariant@0.0.2 --save-exact -w my-cool-package` (hoisted to `node_modules/tiny-invariant`)
1. `npm i tiny-invariant@0.0.3 --save-exact -w my-cool-package` (un-hoisted to `packages/my-cool-package/node_modules/tiny-invariant`, seemingly due to #7019)
1. Edit `packages/my-cool-package/package.json` and change the `tiny-invariant` version to `1.3.1`
1. Run `npm i`
1. Note this package-lock.json inconsistency:
   ```json
    "packages/my-cool-package": {
      "dependencies": {
        "tiny-invariant": "1.3.1"
      }
    },
    "packages/my-cool-package/node_modules/tiny-invariant": {
      "version": "0.0.3",
      "resolved": "https://registry.npmjs.org/tiny-invariant/-/tiny-invariant-0.0.3.tgz",
      "integrity": "sha512-SA2YwvDrCITM9fTvHTHRpq9W6L2fBsClbqm3maT5PZux4Z73SPPDYwJMtnoWh6WMgmCkJij/LaOlWiqJqFMK8g=="
    }

   ```

Note that for steps 1 and 2, you can get the same behavior by editing `packages/my-cool-package/package.json` and running `npm i`; this only stops working once the workspace dependency is already un-hoisted (step 3)

### Environment

- npm: 10.2.4
- Node.js: 18.17.1
- OS Name: Mac OS Ventura
- System Model Name: Macbook Pro
- npm config:
```ini
registry = "https://registry.npmjs.org/"
```

**Comment by stropitek** [comment]
I'm experiencing the same issue, except the package-lock **does NOT** get updated.

I made a reproduction repo with some instructions:

https://github.com/stropitek/npm-overrides-repro

**Comment by jenseng** [comment]
I've confirmed this is fixed in npm 11.2, likely thanks to https://github.com/npm/cli/pull/8089 🥳

**Comment by tumido** [comment]
Hi all, it seems this is not fully fixed — still reproduces on **npm 11.12.1** / node v24.15.0.

Self-contained reproducer (single script, pure npm commands, no pre-existing files):
https://gist.github.com/tumido/13355078978865669dabf4cd998489ce

**Steps:**

1. Root package with `markdownlint-cli2` (devDep, depends on `js-yaml@4.1.1`) + any unrelated `overrides` entry
2. Workspace package starts with no dependencies
3. `npm install js-yaml@4.1.0 -w packages/mylib --save-exact` — works, creates nested `4.1.0`
4. `npm install js-yaml@4.1.1 -w packages/mylib --save-exact` — **silently ignored**, package.json and lockfile both stay at `4.1.0`

Removing `overrides` from root `package.json` and re-running step 4 works correctly — npm deduplicates to a single hoisted `4.1.1`.
