### ISSUE TITLE
[BUG] installing a package with incompatible peer dependencies and `--force` sometimes results in an inf. loop

### ISSUE THREAD

**Issue by G-Rath** [npm/cli#7349]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

On https://github.com/testing-library/eslint-plugin-jest-dom/commit/18afe30adab44a1c3fa96b9669b299178c5517b2 doing `npm i eslint@9 --force` results in an inf. loop outputting:

```
npm WARN node_modules/eslint
npm WARN   peer eslint@"^6.0.0 || ^7.0.0 || >=8.0.0" from @eslint-community/eslint-utils@4.4.0
npm WARN   node_modules/@eslint-community/eslint-utils
npm WARN     @eslint-community/eslint-utils@"^4.2.0" from @typescript-eslint/utils@5.62.0
npm WARN     node_modules/@typescript-eslint/utils
npm WARN     1 more (eslint)
npm WARN   17 more (@typescript-eslint/eslint-plugin, ...)
npm WARN 
npm WARN Could not resolve dependency:
```

Related PR: https://github.com/testing-library/eslint-plugin-jest-dom/pull/355

### Expected Behavior

The install to complete fine, since I've `--force`'d it

### Steps To Reproduce

1. Clone https://github.com/testing-library/eslint-plugin-jest-dom
2. Run `npm i eslint@9 --force`
3. Get stuck in a loop

(also see https://github.com/testing-library/eslint-plugin-jest-dom/actions/runs/8586049626/job/23528114426?pr=355)

### Environment

- npm: 10.5.1
- Node.js: v16.20.2 (also at least happens on 18 too)
- OS Name: Ubuntu
- System Model Name: -
- npm config: -
```ini
; copy and paste output from `npm config ls` here
```

**Comment by G-Rath** [comment]
It seems that if I remove the explicit dependency on `@typescript-eslint/parser` then the inf. loop is resolved even though the same resulting version of `@typescript-eslint/parser` is installed due to child dependencies

**Comment by milaninfy** [comment]
Reproduction steps: 
1.  create a new project
```
{
  "name": "eslint-plugin-jest-dom",
  "version": "0.1.0",
  "dependencies": {
    "@typescript-eslint/parser": "^5.9.1",
    "eslint": "^9.2.0",
    "kcd-scripts": "^12.0.0"
  }
}
```
2.  `npm install --force`
3.  `npm install eslint@9 --force`
4.  see the infinite logs

**Comment by wraithgar** [comment]
~Tested against `latest` and this is no longer happening w/ the example repo.  This was fixed by https://github.com/npm/cli/pull/7499~

Sorry, missed the `eslint@9` step. This is still happening.

**Comment by Santoshraj2** [comment]
The issue is in build-ideal-tree.js the buildDepStep() function is basically have code to check depsQueue if the queue has some dependency, it is recursively calling buildDepStep().. In this scenario the queue is never getting empty because of which it is going in infinite loop.
Since it’s not resolving proper dependency it keeps on adding.  We need to find some break conditions if someone is using --force in command.

**Comment by q-stefanorzu** [comment]
I am seeing this behaviour happening in my project too. I have a fairly big library which depends on another 3rd party library whose transitive deps point to different major versions of React. It's a pretty messy situation, but I can't get rid of this 3rd party lib since it's a hard business requirement.

When a consumer project imports my library, `npm install` does the infinite loop thing and I can't get around it unless:

- the consumer project declares the 3rd party library as a direct dependency, or pin the React version in `overrides` - I still get warnings about the conflicting peer dependencies related to React, but the installation succeeds, OR
- the consumer project runs `npm install` with the `legacy-peer-deps` flag

None of the workarounds are ideal since I'm putting burden on the consumer to do extra steps to use my library. Also, using `legacy-peer-deps` is a bit of an anti-pattern in my view, since it tends to mask other legitimate issues that could otherwise be solvable.

It would be great if someone fixed this infinite loop behaviour, as this can severely disrupt pipelines without giving any useful information to what's actually gone wrong with the installation.
