### ISSUE TITLE
[BUG] `npx fcy`

### ISSUE THREAD

**Issue by lorypelli** [npm/cli#7974]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

using a specific version (1.1.17) fails while using latest doesn't fail

### Expected Behavior

it should work...

### Steps To Reproduce

try using `npx fcy@1.1.17` and after that `npx fcy@latest` both on windows powershell

### Environment

- npm: 10.9.2
- Node.js: 23.3.0
- OS Name: Windows 11
- System Model Name: HP Gaiming
- npm config:
```ini
; node bin location = C:\Program Files\nodejs\node.exe
; node version = v23.3.0
; npm local prefix = D:\Progetti\server
; npm version = 10.9.2
; cwd = D:\Progetti\server
; HOME = C:\Users\<username>
; Run `npm config ls -l` to show all defaults.
```

**Comment by lorypelli** [comment]
ehm...the problem seems to happen only in visual studio code built-in powershell terminal
```
PS D:\Progetti\server> npx fcy@latest
(node:16192) ExperimentalWarning: CommonJS module C:\Users\<username>\.bun\install\global\node_modules\npm\node_modules\debug\src\node.js is loading ES Module C:\Users\<username>\.bun\install\global\node_modules\npm\node_modules\supports-color\index.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Do you want to use defaults options? [Y/n]:   ERROR   ExecaError: Command failed with exit code 1: "C:\Users\<username>\AppData\Local\Temp\server.exe"
PS D:\Progetti\server> npx fcy@1.1.17
(node:2432) ExperimentalWarning: CommonJS module C:\Users\<username>\.bun\install\global\node_modules\npm\node_modules\debug\src\node.js is loading ES Module C:\Users\<username>\.bun\install\global\node_modules\npm\node_modules\supports-color\index.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
"fcy" non è riconosciuto come comando interno o esterno,
 un programma eseguibile o un file batch.
 ```

**Comment by kchindam-infy** [comment]
@lorypelli We have gone through the issue u mention we are not able to see expected behaviour which u mentioned there is an issue from npx fcy@1.1.17.please provide valid information or steps to reproduce the issue. i have attached a file please go through it.
<img width="1015" alt="Screenshot 2024-12-11 at 12 05 51 AM" src="https://github.com/user-attachments/assets/91dcc138-d71a-4b1f-8f28-4bba803ff6b1">

**Comment by lorypelli** [comment]
> @lorypelli We have gone through the issue u mention we are not able to see expected behaviour which u mentioned there is an issue from npx fcy@1.1.17.please provide valid information or steps to reproduce the issue. i have attached a file please go through it.
> <img width="1015" alt="Screenshot 2024-12-11 at 12 05 51 AM" src="https://github.com/user-attachments/assets/91dcc138-d71a-4b1f-8f28-4bba803ff6b1">
> 

It happens with windows powershell and on visual studio code only

**Comment by lorypelli** [comment]
You would need to use Windows to replicate

**Comment by lorypelli** [comment]
Any updates?

**Comment by lorypelli** [comment]
new version I just published  seems to work, the other was removed, versioning is not important in this package so I keep only the latest one...

**Comment by lorypelli** [comment]
any idea of why that happened?

**Comment by milaninfy** [comment]
Not an issue on latest npm and it correctly executes the package. 
Tested on windows and mac. works on both. 
using specific version still doesn't work and that is because this package only has one version 
``` sh
~/npm/cli $ npm view fcy versions 
2.1.6
```
