### ISSUE TITLE
[BUG] npm complains not knowing command 'pm' under pwsh7

### ISSUE THREAD

**Issue by jessehouwing** [npm/cli#8528]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### This issue exists in the latest npm version

- [x] I am using the latest npm

### Current Behavior

This may have been solved in the most recent version, but I can't consistently fic the issue on GitHub Actions Hosted Runners.

When using Node 22.18.0, without updating npm the following is true, and updating npm in the workflow also fails.

When running 

```
& npm install tfx-cli@latest -g
```

Using Node 22, latest npm, I get the following error message:

```
& npm install tfx-cli@latest -g

Unknown command: "pm"

To see a list of supported npm commands, run:
  npm help
```

Removing the `&` in this case fixes the issue.  

```
npm install tfx-cli@latest -g
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated glob@7.1.2: Glob versions prior to v9 are no longer supported
npm warn deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

added 218 packages in 16s 
```

This issue was recently introduced and started breaking existing scripts. 

Similarly `& "npm"` install will now also fail.

When upgrading npm as part of my GitHub Actions workflow, the behavior stays the same. Locally, when upgrading npm to latest, the issue goes away.

### Expected Behavior

```
& "npm" install
& npm install
npm install
```

all work without complaining about missing files or unknown commands

### Steps To Reproduce

The following GitHub Actions woprkflow shows the problem: 

```
name: Show npm issue

on:
  workflow_dispatch:

jobs:

  update:

    runs-on: windows-latest

    steps:
      - name: Use node 22
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22

      - name: Download recent extensions
        run: |
          & npm install npm@latest -g
```

https://github.com/renovatebot/azure-devops-marketplace/actions/runs/17211796029/job/48825249286 

Even adding an explicit update to latest npm in the workflow fails: 

https://github.com/renovatebot/azure-devops-marketplace/actions/runs/17213248909/job/48830235233

### Environment

 azure-devops-marketplace  npm -v                                                                                                             
10.9.3
 azure-devops-marketplace  node -v                                                                                                            
v22.18.0 

Windows 11 24h2 x64

**Comment by jessehouwing** [comment]
I suspect the issue is caused by the fact that the shims aren't recreated when npm is updating itself?

**Comment by jessehouwing** [comment]
Removing the shim and reinstalling npm from a windows shell, solves the issue. 
```
      - run:  (get-command npm).source | remove-item
      - name: Download recent extensions
        run: |
          npm -v
          npm install npm@latest -g 
          npm -v
        shell: cmd
      - name: Download recent extensions
        run: | 
          npm -v
          & npm install tfx-cli@latest -g
```

**Comment by alexsch01** [comment]
good catch, I linked a PR that fixes this

**Comment by jessehouwing** [comment]
@alexsch01 does that solve the case where a bad shim is present and npm is updated too?

**Comment by alexsch01** [comment]
probably, don't know why you are including the "&" in front of the npm command
but my PR should fix it for ya

**Comment by jessehouwing** [comment]
Generally when calling a external tool in powershell, like a cli or anything, that's a common practice. It also allows you to run "npm" when it is passed with quotes. Or to execute a whole string as a command + parameters.

The fact that you're intercepting that by putting npm.ps1 into the path and I'm not calling an executable, but another Powershell script is what threw me off.

This is also a remnant from way back when npm didn't generate a PS1, in that case it would have it execute the .cmd instead.

**Comment by jessehouwing** [comment]
But I think it doesn't fix the issue when upgrading from a previous version of npm when npm came with the node distribution.

Cause when I install Node 20 at the moment, the PS1 shim is broken. When I upgrade NFM, the shim isn't replaced.

When I remove the shim and upgrade npm, the shim *is* replaced. 

So it looks like fixing the shim in npm 11 won't fix users who are on an older version of npm and perform an in-place upgrade.

**Comment by alexsch01** [comment]
@jessehouwing my PR is for the eventual goal of getting the PS1 change into NodeJS 22/24

doing npm i -g npm wouldn't fix that since npm installing a package generates a cmd-shim for the package

`bin/npm.ps1` and `bin/npx.ps1` files in the npm/cli repo are really for just NodeJS to ship them
